import { useEffect, useState } from "react"
import type { PublicImage } from "../../models/GeneratedImage";
import { getPublicImageAPI } from "../../services/GeneratedImageService";
import ImageCard from "../../components/ui/Card/ImageCard";

const Community = () => {
  const [images, setImages] = useState<PublicImage[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchPublicImages = async () => {
      try {
        const publicImages = await getPublicImageAPI();
        if (publicImages) {
          setImages(publicImages);
        }
      } catch (error) {
        setError("Failed to load community creations. Please try again later.");
        console.error(error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchPublicImages();
  }, []);

  const renderContent = () => {
    if (isLoading) {
      return (
        <div className="text-center text-gray-500">
          <svg className="animate-spin h-8 w-8 text-blue-500 mx-auto" viewBox="0 0 24 24">...</svg>
          <p className="mt-2">Loading Creations...</p>
        </div>
      );
    }

    if (error) {
      return <p className="text-center text-red-500">{error}</p>;
    }

    if (images.length === 0) {
      return <p className="text-center text-gray-500">No public images have been created yet. Be the first!</p>;
    }

    return (
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        {images.map((image) => (
          <ImageCard key={image.id} image={image} />
        ))}
      </div>
    );
  };

  return (
    <div className="min-h-screen bg-gary-50 p-8">
      <div className="max-w-7xl mx-auto">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-800">Community Creations</h1>
          <p className="mt-2 text-gray-600">Explore images generated by our creative community.</p>
        </div>
        {renderContent()}
      </div>
    </div>
  );
};

export default Community;
