interface DisplayImageProps {
    imageUrl: string;
    onGenerateAnother: () => void;
}

const DisplayImage = ({
    imageUrl,
    onGenerateAnother,
}: DisplayImageProps) => {
  return (
    <div className="bg-white p-8 rounded-lg shadow-md border border-gray-200 flex flex-col items-center justify-center">
      <h2 className="text-2xl font-bold text-gray-800 mb-6 self-start">
        Your Generated Image
      </h2>
      <img src={imageUrl} alt="Generated by AI" className="max-w-full max-h-[400px] rounded-md object-contain mb-6" />
      <button
        onClick={onGenerateAnother}
        className="w-full bg-[var(--primary-color)] text-white font-bold py-3 px-4 rounded-md hover:bg-green-800 transition-colors"
      >
        Generate Another Image
      </button>
    </div>
  )
}

export default DisplayImage
